// @ts-check
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';

import tailwindcss from '@tailwindcss/vite';

// `site` is required for sitemap generation and for absolute URLs in schema.
// Update it if the production domain ever changes.
const SITE = 'https://buenavistarecovery.com';

/* Pages deliberately kept OUT of the XML sitemap.

   /programs/intensive-outpatient-iop/
     Carries noindex. Admissions states we do not run an IOP; the page exists as
     an honest referral page only. Including it would invite indexing of a
     service we do not offer.

   /404
     Never belongs in a sitemap.
*/
const EXCLUDE = [
  '/programs/intensive-outpatient-iop/',
  '/404/',
];




/* MIGRATION REDIRECTS — 485 rules, generated from the live WordPress
   sitemap (469 URLs) plus 12 months of Search Console data (507 URLs with
   traffic). Regenerate rather than hand-edit; the sources are
   redirect-map-draft.csv and gsc-coverage.csv in the repo root.

   Two rules worth understanding before changing anything here:

   /locations/scottsdale-arizona/ earns 1,092 clicks a year at an average
   position of 5.4 for a facility that is CLOSED. It points at the Scottsdale
   service-area page rather than at Chandler, so the ranking has somewhere to
   land and nobody is sent to a locked door.

   21 blog posts were migrated and keep their URLs, because they carry 4,876 of
   the 5,580 annual blog clicks. The other ~330 route by topic to the relevant
   treatment page.
*/
const MIGRATION_REDIRECTS = {
    '/about-us/': '/about/',
    '/about-us/faq/': '/admissions/',
    '/about-us/our-vision-mission-and-values/': '/about/',
    '/about-us/staff/': '/about/',
    '/about-us/staff/cindy-sneller/': '/about/',
    '/about-us/staff/dr-paul-r-valbuena/': '/about/',
    '/about-us/staff/jill-byron/': '/',
    '/about-us/staff/jose-leon/': '/about/',
    '/about-us/staff/julie-gable/': '/about/',
    '/about-us/staff/katie-noetzel/': '/about/',
    '/about-us/staff/luca-miller-bvr-alumni/': '/',
    '/about-us/staff/lynn-santella/': '/about/',
    '/about-us/staff/mike-kalesk/': '/',
    '/about-us/staff/roxanne-maloney/': '/about/',
    '/about-us/staff/sara-cothern-lcsw/': '/about/',
    '/about-us/staff/tj-carlini/': '/about/',
    '/about-us/travel-help/': '/locations/chandler/',
    '/about-us/why-buena-vista/': '/about/',
    '/addiction-treatment/': '/programs/',
    '/addiction-treatment/for-a-loved-one/': '/for-families/',
    '/addiction-treatment/for-me/': '/programs/',
    '/addiction-treatment/get-started/': '/admissions/',
    '/blog/': '/resources/',
    '/blog/2023/08/': '/blog/',
    '/blog/2024/09/': '/blog/',
    '/blog/2024/10/': '/blog/',
    '/blog/5-common-causes-of-addiction-and-how-to-cope-with-them/': '/blog/',
    '/blog/5-ways-to-support-a-loved-one-in-rehab/': '/for-families/',
    '/blog/9-causes-of-alcohol-addiction-that-make-young-men-need-alcohol-rehab/': '/what-we-treat/alcohol-addiction/',
    '/blog/a-story-of-redemption-with-garrett-deetz/': '/blog/',
    '/blog/addiction-recovery-care/': '/insurance/',
    '/blog/addictions-and-recovery-relapse-prevention/': '/insurance/',
    '/blog/addressing-the-social-needs-of-men-in-recovery/': '/insurance/',
    '/blog/aerobic-exercise-and-addiction-recovery/': '/insurance/',
    '/blog/alcohol-addiction-personality-traits/': '/what-we-treat/alcohol-addiction/',
    '/blog/alcohol-addiction/': '/what-we-treat/alcohol-addiction/',
    '/blog/alcohol-detox-alcoholism/': '/what-we-treat/alcohol-addiction/',
    '/blog/alcohol-detox-arizona/': '/what-we-treat/alcohol-addiction/',
    '/blog/alcohol-detox-program/': '/what-we-treat/alcohol-addiction/',
    '/blog/alcohol-detox-treatment/': '/what-we-treat/alcohol-addiction/',
    '/blog/alcohol-effects/': '/what-we-treat/alcohol-addiction/',
    '/blog/alcohol-withdrawal/': '/what-we-treat/alcohol-addiction/',
    '/blog/alumni-program/': '/programs/aftercare/',
    '/blog/anxiety-and-distress-two-signs-of-opioid-addiction/': '/what-we-treat/opioid-addiction/',
    '/blog/anxiety-medications-and-addiction-when-treatment-makes-it-worse/': '/what-we-treat/anxiety/',
    '/blog/arizona-rehab-campus-in-tucson-finding-treatment-and-the-right-facility/': '/blog/',
    '/blog/art-therapy-and-alcohol-addiction-how-does-it-work/': '/what-we-treat/alcohol-addiction/',
    '/blog/attending-an-addiction-treatment-center-why-men-struggle-to-reach-out-for-help/': '/residential-treatment/',
    '/blog/balancing-pain-management-in-addiction-recovery/': '/insurance/',
    '/blog/balancing-the-costs-of-addiction/': '/insurance/',
    '/blog/balancing-work-while-in-addiction-recovery/': '/insurance/',
    '/blog/behavioral-health-tucson/': '/blog/',
    '/blog/benefits-of-rehab/': '/blog/',
    '/blog/binge-drinking-and-men-where-to-find-a-quality-alcohol-detox-program/': '/what-we-treat/alcohol-addiction/',
    '/blog/blog-substance-use-disorders-and-domestic-violence/': '/blog/',
    '/blog/blog/': '/blog/',
    '/blog/breaking-the-cycle-understanding-addiction-beyond-choice/': '/blog/',
    '/blog/buena-vista-playbook-processing-grief-during-recovery/': '/insurance/',
    '/blog/buena-vista-playbook-what-are-the-benefits-of-anger-management/': '/blog/',
    '/blog/buena-vista-playbook-what-do-sober-people-do-for-fun/': '/blog/',
    '/blog/buena-vista-recovery-playbook-embracing-the-outdoors-in-recovery-this-spring/': '/insurance/',
    '/blog/buena-vista-recovery-providing-inspiration-hope-in-addiction/': '/insurance/',
    '/blog/building-healthier-habits-at-buena-vista-recovery/': '/insurance/',
    '/blog/building-long-term-solutions-starts-with-alcohol-detox/': '/what-we-treat/alcohol-addiction/',
    '/blog/can-a-dui-lead-to-trauma/': '/what-we-treat/alcohol-addiction/',
    '/blog/can-health-insurance-pay-for-my-rehab-expenses/': '/insurance/',
    '/blog/can-i-manage-addiction-while-still-attending-college/': '/blog/',
    '/blog/can-i-overcome-my-addiction-with-an-outpatient-treatment-program/': '/blog/',
    '/blog/can-i-pursue-love-in-recovery/': '/insurance/',
    '/blog/can-i-use-insurance-to-pay-for-drug-and-alcohol-rehab/': '/what-we-treat/alcohol-addiction/',
    '/blog/can-learning-yoga-in-xanax-addiction-recovery-improve-your-outcome/': '/what-we-treat/benzodiazepine-addiction/',
    '/blog/can-reconnecting-with-your-emotions-at-iop-arizona-help-you-heal/': '/blog/',
    '/blog/can-you-fail-rehab-what-that-actually-means/': '/blog/',
    '/blog/can-you-overcome-a-meth-addiction/': '/what-we-treat/stimulant-addiction/',
    '/blog/causes-effects-and-overcoming-crystal-meth-addiction/': '/what-we-treat/stimulant-addiction/',
    '/blog/celebrating-valentines-day-in-recovery/': '/insurance/',
    '/blog/childhood-trauma-and-addiction/': '/dual-diagnosis/',
    '/blog/choosing-a-detox-center-does-the-treatment-environment-really-matter/': '/medical-detox/',
    '/blog/co-occurring-disorders-among-men/': '/dual-diagnosis/',
    '/blog/co-occurring-disorders-and-substance-abuse/': '/dual-diagnosis/',
    '/blog/cocaine-detox-the-first-step-to-a-more-secure-life/': '/what-we-treat/stimulant-addiction/',
    '/blog/cocaine-detox-the-start-of-a-new-lifestyle/': '/what-we-treat/stimulant-addiction/',
    '/blog/cocaine-vs-meth-which-is-harder-to-quit/': '/what-we-treat/stimulant-addiction/',
    '/blog/cognitive-behavioral-therapy-exercises/': '/therapies/',
    '/blog/combating-seasonal-affective-disorder-for-relapse-prevention/': '/programs/aftercare/',
    '/blog/committing-yourself-to-a-continuum-of-addiction-care/': '/blog/',
    '/blog/common-signs-of-addiction/': '/blog/',
    '/blog/commonly-used-short-acting-opioids-list/': '/what-we-treat/opioid-addiction/',
    '/blog/complications-of-alcohol-withdrawal/': '/what-we-treat/alcohol-addiction/',
    '/blog/contingency-nanagement-therapy-effective-addiction-treatment-barriers/': '/therapies/',
    '/blog/continuing-therapy-after-drug-and-alcohol-treatment/': '/what-we-treat/alcohol-addiction/',
    '/blog/coping-skills-for-addiction/': '/blog/',
    '/blog/creating-a-personalized-addiction-treatment-plan/': '/blog/',
    '/blog/creating-effective-boundaries-with-workplace-peers/': '/about/',
    '/blog/dependence-on-xanax/': '/what-we-treat/benzodiazepine-addiction/',
    '/blog/detox-in-chandler-same-day-admissions-available/': '/medical-detox/',
    '/blog/dialectical-behavior-therapy/': '/therapies/',
    '/blog/dieting-and-healthy-eating-habits-in-addiction-recovery/': '/insurance/',
    '/blog/different-types-of-addictions-opiates-and-treatments/': '/what-we-treat/opioid-addiction/',
    '/blog/distinguishing-between-self-care-and-aftercare/': '/programs/aftercare/',
    '/blog/do-i-have-to-quit-my-job-for-detox-and-recovery/': '/medical-detox/',
    '/blog/do-i-need-xanax-addiction-treatment/': '/what-we-treat/benzodiazepine-addiction/',
    '/blog/do-parents-know-the-signs-of-opioid-addiction/': '/what-we-treat/opioid-addiction/',
    '/blog/does-age-impact-addiction-and-recovery/': '/insurance/',
    '/blog/does-alcoholics-anonymous-actually-work/': '/what-we-treat/alcohol-addiction/',
    '/blog/does-my-husband-need-to-seek-an-addiction-treatment-center/': '/for-families/',
    '/blog/does-your-adult-child-need-medical-detox/': '/for-families/',
    '/blog/dos-and-donts-to-follow-when-your-loved-one-is-struggling-with-addiction/': '/for-families/',
    '/blog/drug-addiction-treatment-how-to-stay-away-from-drugs-and-avoid-relapse/': '/programs/aftercare/',
    '/blog/drug-list-where-detox-is-needed-in-cases-of-addiction/': '/medical-detox/',
    '/blog/dual-diagnosis-how-to-manage-my-mental-health-and-addiction-treatment/': '/dual-diagnosis/',
    '/blog/dual-diagnosis-rehab/': '/dual-diagnosis/',
    '/blog/dual-diagnosis-treatment-arizona/': '/dual-diagnosis/',
    '/blog/embracing-vulnerability-is-part-of-drug-and-alcohol-treatment/': '/what-we-treat/alcohol-addiction/',
    '/blog/facing-cocaine-detox-fears/': '/what-we-treat/stimulant-addiction/',
    '/blog/fear-of-leaving-rehab/': '/blog/',
    '/blog/fentanyl-addiction-signs-why-early-intervention-is-critical/': '/what-we-treat/opioid-addiction/fentanyl/',
    '/blog/fentanyl-addiction-signs/': '/what-we-treat/opioid-addiction/fentanyl/',
    '/blog/fentanyl-overdose-why-is-fentanyl-so-dangerous/': '/what-we-treat/opioid-addiction/fentanyl/',
    '/blog/finding-addiction-treatment-centers-after-a-dui/': '/what-we-treat/alcohol-addiction/',
    '/blog/finding-help-from-an-addiction-treatment-center/': '/residential-treatment/',
    '/blog/finding-hope-what-to-do-after-a-relapse/': '/programs/aftercare/',
    '/blog/finding-the-courage-to-receive-treatment-at-an-arizona-recovery-center/': '/insurance/',
    '/blog/from-the-grave-to-grace-the-burning-bush/': '/blog/',
    '/blog/functional-alcoholism/': '/what-we-treat/alcohol-addiction/',
    '/blog/gallery/': '/blog/',
    '/blog/getting-help-at-buena-vista-for-a-dual-diagnosis-as-a-man/': '/dual-diagnosis/',
    '/blog/glossary/adderall/': '/what-we-treat/stimulant-addiction/',
    '/blog/glossary/addiction/': '/blog/',
    '/blog/glossary/alcohol/': '/what-we-treat/alcohol-addiction/',
    '/blog/glossary/ayahuasca/': '/blog/',
    '/blog/glossary/bath-salts/': '/blog/',
    '/blog/glossary/benzodiazepines/': '/what-we-treat/benzodiazepine-addiction/',
    '/blog/glossary/buprenorphine/': '/blog/',
    '/blog/glossary/cocaine/': '/what-we-treat/stimulant-addiction/',
    '/blog/glossary/codeine/': '/what-we-treat/opioid-addiction/',
    '/blog/glossary/depression/': '/what-we-treat/depression/',
    '/blog/glossary/dui/': '/what-we-treat/alcohol-addiction/',
    '/blog/glossary/dwi/': '/blog/',
    '/blog/glossary/ecstasy-mdma/': '/blog/',
    '/blog/glossary/fentanyl/': '/what-we-treat/opioid-addiction/fentanyl/',
    '/blog/glossary/heroin/': '/what-we-treat/opioid-addiction/',
    '/blog/glossary/hydrocodone-facts/': '/what-we-treat/opioid-addiction/',
    '/blog/glossary/ketamine/': '/blog/',
    '/blog/glossary/marijuana/': '/blog/',
    '/blog/glossary/methamphetamine/': '/what-we-treat/stimulant-addiction/',
    '/blog/glossary/naloxone/': '/what-we-treat/opioid-addiction/',
    '/blog/glossary/opioids/': '/what-we-treat/opioid-addiction/',
    '/blog/glossary/oxycodone/': '/what-we-treat/opioid-addiction/',
    '/blog/glossary/painkillers/': '/blog/',
    '/blog/glossary/suboxone/': '/what-we-treat/opioid-addiction/',
    '/blog/glossary/withdrawal/': '/medical-detox/',
    '/blog/grief-therapy-for-addiction-recovery/': '/therapies/',
    '/blog/grief-therapy-for-addiction/': '/therapies/',
    '/blog/group-therapy/': '/therapies/',
    '/blog/hallucinogenic-drugs-example-list-how-it-affect-ones-brain-and-health/': '/blog/',
    '/blog/hallucinogens-long-term-effects/': '/blog/',
    '/blog/handling-inpatient-substance-abuse-treatment-with-kids/': '/residential-treatment/',
    '/blog/healing-from-addiction-and-childhood-trauma-at-buena-vista-recovery/': '/dual-diagnosis/',
    '/blog/heroin-addiction/': '/what-we-treat/opioid-addiction/',
    '/blog/heroin-withdrawal-symptoms-medication/': '/what-we-treat/opioid-addiction/',
    '/blog/heroin-withdrawal-timeline/': '/what-we-treat/opioid-addiction/',
    '/blog/how-alcohol-addiction-complicates-your-finances-before-alcohol-detox/': '/what-we-treat/alcohol-addiction/',
    '/blog/how-antidepressants-can-help-you-recover-from-addiction/': '/what-we-treat/depression/',
    '/blog/how-buena-vista-helps-men-develop-self-care-strategies/': '/blog/',
    '/blog/how-buena-vistas-opioid-treatment-program-helps-you-make-amends/': '/what-we-treat/opioid-addiction/',
    '/blog/how-can-a-routine-help-me-thrive-after-addiction-treatment/': '/blog/',
    '/blog/how-can-an-iop-in-arizona-help-you-cope-with-stress-at-work/': '/about/',
    '/blog/how-can-buena-vista-recovery-help-my-adult-child-fight-addiction/': '/for-families/',
    '/blog/how-can-i-celebrate-success-in-sobriety/': '/blog/',
    '/blog/how-can-i-develop-a-healthy-sober-relationship-in-recovery/': '/for-families/',
    '/blog/how-can-i-find-purpose-after-inpatient-substance-abuse-treatment/': '/residential-treatment/',
    '/blog/how-can-i-give-back-to-the-recovery-community/': '/insurance/',
    '/blog/how-can-i-support-a-loved-one-in-recovery/': '/for-families/',
    '/blog/how-can-immediate-relief-at-buena-vista-help-with-lasting-recovery/': '/insurance/',
    '/blog/how-can-iops-help-me-maintain-sobriety/': '/blog/',
    '/blog/how-different-types-of-addiction-impact-your-sleep/': '/blog/',
    '/blog/how-difficult-is-cocaine-detox/': '/what-we-treat/stimulant-addiction/',
    '/blog/how-do-i-adjust-to-life-after-dui-jail-time/': '/what-we-treat/alcohol-addiction/',
    '/blog/how-do-i-choose-the-right-rehab/': '/blog/',
    '/blog/how-do-i-create-a-daily-routine-in-an-intensive-outpatient-program/': '/blog/',
    '/blog/how-do-i-create-a-relapse-prevention-plan-in-recovery/': '/insurance/',
    '/blog/how-do-i-explain-dui-jail-time-to-my-family/': '/what-we-treat/alcohol-addiction/',
    '/blog/how-do-i-set-boundaries-with-old-friends-after-opioid-treatment/': '/what-we-treat/opioid-addiction/',
    '/blog/how-do-i-support-my-son-through-alcohol-addiction-treatment/': '/what-we-treat/alcohol-addiction/',
    '/blog/how-do-mental-health-disorders-inform-addiction/': '/dual-diagnosis/',
    '/blog/how-do-pain-management-and-fentanyl-addiction-connect/': '/what-we-treat/opioid-addiction/fentanyl/',
    '/blog/how-does-a-healthy-diet-improve-mental-health/': '/dual-diagnosis/',
    '/blog/how-does-language-affect-my-addiction-recovery/': '/insurance/',
    '/blog/how-does-pain-management-in-addiction-recovery-work/': '/insurance/',
    '/blog/how-does-sleep-help-with-pain-management-in-addiction-recovery/': '/insurance/',
    '/blog/how-does-social-media-impact-my-addiction-recovery/': '/insurance/',
    '/blog/how-does-spirituality-in-recovery-affect-me/': '/insurance/',
    '/blog/how-family-support-helps-in-addiction-treatment/': '/for-families/',
    '/blog/how-individual-therapy-can-build-your-social-support-network/': '/therapies/',
    '/blog/how-learning-to-manage-stress-helps-with-fentanyl-overdose-prevention/': '/what-we-treat/opioid-addiction/fentanyl/',
    '/blog/how-long-do-drugs-stay-in-your-system/': '/blog/',
    '/blog/how-long-do-opioids-stay-in-your-system/': '/what-we-treat/opioid-addiction/',
    '/blog/how-long-does-addiction-recovery-take/': '/insurance/',
    '/blog/how-long-does-alcohol-stay-in-your-system/': '/what-we-treat/alcohol-addiction/',
    '/blog/how-long-does-alcohol-withdrawal-last/': '/what-we-treat/alcohol-addiction/',
    '/blog/how-long-does-fentanyl-stay-in-your-system/': '/what-we-treat/opioid-addiction/fentanyl/',
    '/blog/how-long-does-it-take-to-detox-from-alcohol/': '/what-we-treat/alcohol-addiction/',
    '/blog/how-long-does-xanax-stay-in-your-system/': '/what-we-treat/benzodiazepine-addiction/',
    '/blog/how-opioid-treatment-helps-men-manage-panic-disorder-while-sober/': '/what-we-treat/opioid-addiction/',
    '/blog/how-physical-trauma-affects-addiction/': '/dual-diagnosis/',
    '/blog/how-to-approach-a-loved-one-about-his-or-her-addiction/': '/for-families/',
    '/blog/how-to-break-old-habits-after-leaving-an-addiction-treatment-center/': '/residential-treatment/',
    '/blog/how-to-build-a-positive-supportive-network-in-addiction-recovery/': '/insurance/',
    '/blog/how-to-choose-the-best-inpatient-substance-abuse-treatment/': '/residential-treatment/',
    '/blog/how-to-combat-social-anxiety/': '/what-we-treat/anxiety/',
    '/blog/how-to-cultivate-self-confidence-following-alcohol-detox-and-treatment/': '/what-we-treat/alcohol-addiction/',
    '/blog/how-to-decide-if-a-12-step-program-is-right-for-me/': '/therapies/',
    '/blog/how-to-get-help-for-addiction-where-to-start-and-what-you-need-to-do/': '/blog/',
    '/blog/how-to-handle-holiday-stress-in-recovery/': '/insurance/',
    '/blog/how-to-pay-for-rehab-in-arizona-what-are-your-options/': '/insurance/',
    '/blog/how-to-prepare-before-entering-an-addiction-treatment-center/': '/residential-treatment/',
    '/blog/how-to-prepare-for-a-dui-court-hearing/': '/what-we-treat/alcohol-addiction/',
    '/blog/how-to-stay-inspired-to-change-after-drug-and-alcohol-treatment/': '/what-we-treat/alcohol-addiction/',
    '/blog/how-to-tell-if-a-rehab-center-is-actually-clinical/': '/residential-treatment/',
    '/blog/how-will-dui-jail-time-affect-my-recovery/': '/what-we-treat/alcohol-addiction/',
    '/blog/how-will-recovery-affect-my-job/': '/insurance/',
    '/blog/how-young-men-can-build-self-esteem-following-alcohol-rehab/': '/what-we-treat/alcohol-addiction/',
    '/blog/how-your-diet-affects-addiction-recovery/': '/insurance/',
    '/blog/hydrocodone-addiction/': '/what-we-treat/opioid-addiction/',
    '/blog/hydrocodone-and-alcohol/': '/what-we-treat/opioid-addiction/',
    '/blog/hydrocodone-overdose/': '/what-we-treat/opioid-addiction/',
    '/blog/i-finished-alcohol-detox-and-treatment-now-what/': '/what-we-treat/alcohol-addiction/',
    '/blog/identifying-different-types-of-addiction-in-young-adults/': '/blog/',
    '/blog/identifying-the-signs-of-marijuana-addiction/': '/blog/',
    '/blog/individualized-care-improves-pain-management-in-addiction-recovery/': '/insurance/',
    '/blog/insurance-plans-that-cover-dual-diagnosis-rehab-programs/': '/dual-diagnosis/',
    '/blog/intensive-outpatient-program/': '/blog/',
    '/blog/introducing-the-buena-vista-recovery-app-join-our-community/': '/insurance/',
    '/blog/is-addiction-genetic/': '/blog/',
    '/blog/is-alcohol-use-among-men-more-common/': '/what-we-treat/alcohol-addiction/',
    '/blog/is-an-intensive-outpatient-program-iop-right-for-me/': '/blog/',
    '/blog/is-cocaine-detox-different-for-men/': '/what-we-treat/stimulant-addiction/',
    '/blog/is-inpatient-or-outpatient-treatment-better-for-a-pain-pill-addiction/': '/residential-treatment/',
    '/blog/is-it-too-late-for-me-to-enter-alcohol-detox-for-my-addiction/': '/what-we-treat/alcohol-addiction/',
    '/blog/is-medication-assisted-treatment-effective/': '/blog/',
    '/blog/is-my-child-struggling-with-addiction/': '/for-families/',
    '/blog/is-my-loved-one-struggling-with-addiction/': '/for-families/',
    '/blog/is-social-anxiety-affecting-my-substance-use/': '/what-we-treat/anxiety/',
    '/blog/keeping-yourself-motivated-throughout-recovery/': '/insurance/',
    '/blog/learning-to-re-imagine-your-life-after-alcohol-detox/': '/what-we-treat/alcohol-addiction/',
    '/blog/legal-issues-associated-with-rehab/': '/blog/',
    '/blog/life-after-rehab-applying-skills-learned-in-rehab-to-your-life/': '/programs/aftercare/',
    '/blog/local-or-out-of-state-drug-detox-center-how-to-decide/': '/medical-detox/',
    '/blog/long-term-effects-of-vicodin-risks-addiction-treatment/': '/what-we-treat/opioid-addiction/',
    '/blog/managing-boredom-in-recovery/': '/insurance/',
    '/blog/mat-for-opioid-use/': '/what-we-treat/opioid-addiction/',
    '/blog/medical-detox-for-alcohol-addiction-and-the-next-steps/': '/what-we-treat/alcohol-addiction/',
    '/blog/medical-detox-overcoming-abuse/': '/medical-detox/',
    '/blog/medication-assisted-treatment/': '/blog/',
    '/blog/meth-addiction-treatment-and-recovery-where-to-find-help/': '/what-we-treat/stimulant-addiction/',
    '/blog/meth-withdrawal-timeline-what-you-need-to-know/': '/what-we-treat/stimulant-addiction/',
    '/blog/mixing-stimulants-and-depressants-dangers-consequences-/': '/what-we-treat/stimulant-addiction/',
    '/blog/most-common-relapse-triggers-and-how-to-manage-them/': '/programs/aftercare/',
    '/blog/myths-about-medication-assisted-treatment/': '/blog/',
    '/blog/natural-insomnia-remedies-stop-counting-sheep-and-start-counting-zzzzs/': '/blog/',
    '/blog/negative-impacts-of-alcohol-on-society/': '/what-we-treat/alcohol-addiction/',
    '/blog/opiate-addiction-treatment-options/': '/what-we-treat/opioid-addiction/',
    '/blog/opiate-detox-timeline/': '/what-we-treat/opioid-addiction/',
    '/blog/opiate-detox-treatment/': '/what-we-treat/opioid-addiction/',
    '/blog/opiod_addiction_and_chronic_pain/': '/blog/',
    '/blog/opioid-overdose-reversal/': '/what-we-treat/opioid-addiction/',
    '/blog/outpatient-rehab-building-a-social-support-network-managing-stress/': '/about/',
    '/blog/overcoming-adverse-childhood-experiences-and-addiction/': '/for-families/',
    '/blog/overcoming-the-effects-of-anger-in-addiction-recovery/': '/insurance/',
    '/blog/overcoming-the-effects-of-seasonal-affective-disorder-sad/': '/blog/',
    '/blog/overcoming-the-stigmas-of-men-pursuing-addiction-treatment/': '/blog/',
    '/blog/page/2/': '/blog/',
    '/blog/page/5/': '/blog/',
    '/blog/parents-with-addiction/': '/for-families/',
    '/blog/partial-hospitalization-program-vs-iop-understand-the-difference/': '/blog/',
    '/blog/podcast-ep-2-meet-bobby-cording/': '/blog/',
    '/blog/preparing-for-detox-setting-expectations/': '/medical-detox/',
    '/blog/prescription-drug-withdrawal-symptoms/': '/medical-detox/',
    '/blog/preventing-relapse-during-quarantine/': '/programs/aftercare/',
    '/blog/recognizing-the-signs-and-symptoms-of-opioid-abuse/': '/what-we-treat/opioid-addiction/',
    '/blog/recollecting-your-life-after-a-dui/': '/what-we-treat/alcohol-addiction/',
    '/blog/rehab-facts-vs-fiction/': '/blog/',
    '/blog/relapse-in-the-recovery-process/': '/insurance/',
    '/blog/relapse-prevention-longer-stays-ongoing-support/': '/programs/aftercare/',
    '/blog/residential-vs-intensive-outpatient-programs-whats-the-difference/': '/residential-treatment/',
    '/blog/returning-to-work-after-substance-abuse-treatment/': '/about/',
    '/blog/scared-to-go-to-rehab/': '/blog/',
    '/blog/sharing-inpatient-substance-abuse-treatment-experience-with-your-wife/': '/for-families/',
    '/blog/should-i-tell-my-family-i-need-to-go-to-an-opioid-treatment-program/': '/what-we-treat/opioid-addiction/',
    '/blog/signs-and-symptoms-of-substance-abuse/': '/blog/',
    '/blog/signs-that-your-loved-one-might-have-an-addiction/': '/for-families/',
    '/blog/signs-you-may-be-nearing-a-fentanyl-overdose/': '/what-we-treat/opioid-addiction/fentanyl/',
    '/blog/suboxone-detox-treatment/': '/what-we-treat/opioid-addiction/',
    '/blog/suboxone-withdrawal/': '/what-we-treat/opioid-addiction/',
    '/blog/substance-abuse-disorder/': '/blog/',
    '/blog/substance-abuse-therapy/': '/therapies/',
    '/blog/substance-abuse-treatment-for-medical-professionals/': '/blog/',
    '/blog/supporting-a-loved-one-through-anxiety-panic-and-addiction/': '/what-we-treat/anxiety/',
    '/blog/taking-charge-of-your-sober-thanksgiving/': '/blog/',
    '/blog/talking-to-a-spouse-about-substance-use/': '/for-families/',
    '/blog/the-2-different-types-of-addiction-with-examples/': '/blog/',
    '/blog/the-benefits-of-group-therapy/': '/therapies/',
    '/blog/the-benefits-of-mindfulness-meditation-during-addiction-treatment/': '/blog/',
    '/blog/the-biology-of-detox/': '/medical-detox/',
    '/blog/the-dangerous-effects-of-depression/': '/what-we-treat/depression/',
    '/blog/the-difference-between-slips-and-relapse-in-recovery/': '/insurance/',
    '/blog/the-differences-between-inpatient-and-outpatient-addiction-treatments/': '/residential-treatment/',
    '/blog/the-different-types-of-goals-to-set-for-2021/': '/blog/',
    '/blog/the-effects-of-addiction-on-children/': '/for-families/',
    '/blog/the-emotional-impact-of-a-dui-conviction/': '/what-we-treat/alcohol-addiction/',
    '/blog/the-good-bad-and-ugly-what-the-road-to-recovery-really-looks-like/': '/insurance/',
    '/blog/the-impact-of-addiction-on-the-family/': '/for-families/',
    '/blog/the-impact-of-dui-jail-time-on-my-recovery/': '/what-we-treat/alcohol-addiction/',
    '/blog/the-importance-of-individualized-therapy-after-dui-jail-time/': '/what-we-treat/alcohol-addiction/',
    '/blog/the-many-forms-of-addiction/': '/blog/',
    '/blog/the-role-of-comfort-and-luxury-in-overcoming-addiction/': '/blog/',
    '/blog/the-role-of-community-in-recovery/': '/insurance/',
    '/blog/the-role-of-community-in-relapse-prevention/': '/programs/aftercare/',
    '/blog/the-role-of-gratitude-in-addiction-recovery/': '/insurance/',
    '/blog/the-story-of-jesus-g-gutierrez/': '/blog/',
    '/blog/tools-for-recovery/': '/insurance/',
    '/blog/trauma-and-its-effects-on-substance-use/': '/dual-diagnosis/',
    '/blog/understanding-addiction-as-a-disease-and-how-it-develops/': '/blog/',
    '/blog/understanding-alcohol-abuse/': '/what-we-treat/alcohol-addiction/',
    '/blog/understanding-psychological-addiction/': '/blog/',
    '/blog/understanding-the-different-alcohol-detox-symptoms/': '/what-we-treat/alcohol-addiction/',
    '/blog/understanding-the-need-for-medical-detox/': '/medical-detox/',
    '/blog/using-cognitive-behavioral-therapy-in-addiction-treatment/': '/therapies/',
    '/blog/using-medication-during-opioid-withdrawal/': '/what-we-treat/opioid-addiction/',
    '/blog/using-technology-to-facilitate-continued-healing/': '/blog/',
    '/blog/vicodin-dependence-short-and-long-term-effects/': '/what-we-treat/opioid-addiction/',
    '/blog/what-actually-happens-in-your-first-72-hours-in-detox/': '/medical-detox/',
    '/blog/what-are-coping-skills-for-different-types-of-addiction/': '/blog/',
    '/blog/what-are-some-drug-and-alcohol-treatment-centers-in-arizona/': '/what-we-treat/alcohol-addiction/',
    '/blog/what-are-the-benefits-of-cognitive-behavioral-therapy-cbt/': '/therapies/',
    '/blog/what-are-the-differences-between-crack-and-cocaine/': '/what-we-treat/stimulant-addiction/',
    '/blog/what-are-the-signs-of-heroin-overdose/': '/what-we-treat/opioid-addiction/',
    '/blog/what-are-the-symptoms-of-alcohol-withdrawal/': '/what-we-treat/alcohol-addiction/',
    '/blog/what-can-i-expect-in-residential-treatment/': '/residential-treatment/',
    '/blog/what-does-treatment-look-like-at-an-arizona-addiction-recovery-center/': '/insurance/',
    '/blog/what-happens-in-outpatient-rehab/': '/blog/',
    '/blog/what-happens-to-my-brain-when-i-become-addicted-to-substances/': '/blog/',
    '/blog/what-happens-when-i-arrive-at-treatment/': '/blog/',
    '/blog/what-is-a-dual-diagnosis/': '/dual-diagnosis/',
    '/blog/what-is-alcohol-detox-medication/': '/what-we-treat/alcohol-addiction/',
    '/blog/what-is-medical-detox/': '/medical-detox/',
    '/blog/what-is-relapse-in-addiction/': '/programs/aftercare/',
    '/blog/what-is-the-biology-of-addiction/': '/blog/',
    '/blog/what-is-the-connection-between-trauma-self-medicating-and-addiction/': '/dual-diagnosis/',
    '/blog/what-is-toxic-positivity-and-how-does-it-affect-addiction-recovery/': '/insurance/',
    '/blog/what-recovery-looks-like-6-months-after-rehab/': '/insurance/',
    '/blog/whats-the-difference-between-stimulants-depressants/': '/what-we-treat/stimulant-addiction/',
    '/blog/when-is-detwhen-is-detox-necessaryox-necessary/': '/medical-detox/',
    '/blog/when-is-it-time-to-call-an-inpatient-rehabilitation-center/': '/residential-treatment/',
    '/blog/which-prescription-drugs-can-lead-to-addiction/': '/blog/',
    '/blog/who-makes-the-most-effective-supports-in-recovery/': '/insurance/',
    '/blog/why-connection-matters-so-much-after-an-intensive-outpatient-program/': '/blog/',
    '/blog/why-do-addicts-relapse-even-if-things-are-good/': '/programs/aftercare/',
    '/blog/why-does-buena-vista-believe-case-management-is-important-in-recovery/': '/insurance/',
    '/blog/why-is-detox-necessary/': '/medical-detox/',
    '/blog/why-is-family-education-important-in-addiction-recovery/': '/for-families/',
    '/blog/why-is-fentanyl-so-dangerous-a-detailed-look/': '/what-we-treat/opioid-addiction/fentanyl/',
    '/blog/why-some-people-get-worse-after-rehab/': '/blog/',
    '/blog/why-you-should-consider-going-out-of-state-for-rehab/': '/blog/',
    '/blog/will-a-fentanyl-overdose-change-my-thought-process-long-term/': '/what-we-treat/opioid-addiction/fentanyl/',
    '/blog/will-alcohol-rehab-help-after-a-dui/': '/what-we-treat/alcohol-addiction/',
    '/blog/will-medication-assisted-treatment-help-after-a-fentanyl-overdose/': '/what-we-treat/opioid-addiction/fentanyl/',
    '/blog/will-my-parents-support-me-through-drug-and-alcohol-treatment/': '/what-we-treat/alcohol-addiction/',
    '/blog/will-trying-a-detox-center-near-me-help/': '/medical-detox/',
    '/blog/will-xanax-detox-have-negative-long-term-effects/': '/what-we-treat/benzodiazepine-addiction/',
    '/blog/work-related-anxiety-and-substance-abuse/': '/what-we-treat/anxiety/',
    '/blog/xanax-addiction-treatment-plan-whats-the-best-option-for-me/': '/what-we-treat/benzodiazepine-addiction/',
    '/blog/xanax-detox-is-it-safe-to-do-at-home/': '/what-we-treat/benzodiazepine-addiction/',
    '/blog/xanax-withdrawal/': '/what-we-treat/benzodiazepine-addiction/',
    '/blog/your-guide-to-physical-addiction-and-how-to-get-help/': '/blog/',
    '/careers/': '/about/careers/',
    '/chandler-facility/': '/',
    '/contact-us/': '/about/contact/',
    '/glossary/': '/resources/',
    '/glossary/adderall/': '/what-we-treat/stimulant-addiction/',
    '/glossary/addiction/': '/blog/',
    '/glossary/ayahuasca/': '/blog/',
    '/glossary/bath-salts/': '/blog/',
    '/glossary/benzodiazepines/': '/what-we-treat/benzodiazepine-addiction/',
    '/glossary/cocaine/': '/what-we-treat/stimulant-addiction/',
    '/glossary/codeine/': '/what-we-treat/opioid-addiction/',
    '/glossary/depression/': '/what-we-treat/depression/',
    '/glossary/dwi/': '/blog/',
    '/glossary/ecstasy-mdma/': '/blog/',
    '/glossary/hydrocodone-facts/': '/what-we-treat/opioid-addiction/',
    '/glossary/ketamine/': '/blog/',
    '/glossary/oxycodone/': '/what-we-treat/opioid-addiction/',
    '/glossary/painkillers/': '/blog/',
    '/glossary/suboxone/': '/what-we-treat/opioid-addiction/',
    '/insurance/aetna-insurance-for-addiction-treatment/': '/insurance/',
    '/insurance/ahcccs-insurance-for-addiction-treatment/': '/insurance/ahcccs-medicaid/',
    '/insurance/beacon-insurance/': '/insurance/',
    '/insurance/bluecross-blueshield-insurance-for-addiction-treatment/': '/insurance/',
    '/insurance/cerner-insurance-for-addiction-treatment/': '/insurance/',
    '/insurance/cigna-insurance-for-addiction-treatment/': '/insurance/',
    '/insurance/compsych-insurance/': '/insurance/',
    '/insurance/first-health-network-insurance/': '/insurance/',
    '/insurance/harvard-pilgrim-insurance/': '/insurance/',
    '/insurance/humana-insurance-for-drug-alcohol-rehab/': '/insurance/',
    '/insurance/in-network/': '/insurance/',
    '/insurance/in-network/american-indian-health-program/': '/insurance/ahcccs-medicaid/',
    '/insurance/in-network/care1st/': '/insurance/ahcccs-medicaid/',
    '/insurance/in-network/usa-mco-insurance/': '/insurance/ahcccs-medicaid/',
    '/insurance/insurance-verification/': '/insurance/verify-your-benefits/',
    '/insurance/kaiser-permanente-insurance/': '/insurance/',
    '/insurance/kaiser_permanente_insurance/': '/',
    '/insurance/magellan-complete-care/': '/insurance/ahcccs-medicaid/',
    '/insurance/mercy-care/': '/insurance/ahcccs-medicaid/',
    '/insurance/multiplan-insurance/': '/insurance/',
    '/insurance/out-of-network/': '/insurance/',
    '/insurance/out-of-network/anthem-bcbs-insurance-for-addiction-treatment/': '/insurance/',
    '/insurance/out-of-network/magellan-health-insurance/': '/insurance/',
    '/insurance/out-of-network/presbyterian-insurance/': '/insurance/',
    '/insurance/out-of-network/tricare/': '/insurance/',
    '/insurance/tufts-health-insurance/': '/insurance/',
    '/insurance/unitedhealthcare-insurance/': '/insurance/',
    '/iop-treatment-arizona/': '/programs/intensive-outpatient-iop/',
    '/locations/alcohol-and-drug-rehab-chandler-az/': '/locations/chandler/',
    '/locations/alcohol-and-drug-rehab-tucson-az/': '/locations/tucson/',
    '/locations/cave-creek/': '/locations/',
    '/locations/scottsdale-arizona/': '/locations/scottsdale/',
    '/locations/who-we-serve/': '/who-we-serve/',
    '/locations/who-we-serve/1182-2/': '/',
    '/locations/who-we-serve/california-substance-abuse-treatment-facility/': '/locations/',
    '/locations/who-we-serve/georgia-substance-abuse-treatment/': '/locations/',
    '/locations/who-we-serve/illinois-rehab-centers/': '/locations/',
    '/locations/who-we-serve/in-state/': '/locations/',
    '/locations/who-we-serve/in-state/998-2/': '/locations/',
    '/locations/who-we-serve/in-state/phoenix-az/': '/locations/phoenix/',
    '/locations/who-we-serve/in-state/scottsdale/': '/locations/',
    '/locations/who-we-serve/nevada-substance-abuse-treatment/': '/locations/',
    '/locations/who-we-serve/new-mexico-rehab-facility/': '/locations/',
    '/locations/who-we-serve/new-york-substance-abuse-treatment/': '/locations/',
    '/locations/who-we-serve/out-of-state/': '/locations/',
    '/locations/who-we-serve/out-of-state/colorado-drug-rehab-center/': '/locations/',
    '/locations/who-we-serve/out-of-state/florida-drug-rehab-centers/': '/locations/',
    '/locations/who-we-serve/out-of-state/utah-substance-abuse-treatment/': '/locations/',
    '/locations/who-we-serve/texas-drug-rehab-center/': '/locations/',
    '/notice-of-privacy-practices/': '/',
    '/our-programs/': '/programs/',
    '/our-programs/buena-vista-alumni-program/': '/programs/aftercare/',
    '/our-programs/inpatient/': '/residential-treatment/',
    '/our-programs/inpatient/alcoholism/': '/what-we-treat/alcohol-addiction/',
    '/our-programs/inpatient/substance-abuse/': '/residential-treatment/',
    '/our-programs/iop-treatment-arizona/': '/programs/intensive-outpatient-iop/',
    '/our-programs/medical-detox/': '/medical-detox/',
    '/our-programs/medical-detox/alcohol-detox/': '/what-we-treat/alcohol-addiction/',
    '/our-programs/medical-detox/drug-detox/': '/medical-detox/',
    '/our-programs/medical-detox/drug-detox/opioid-drug-detox/': '/what-we-treat/opioid-addiction/',
    '/our-programs/medical-detox/drug-detox/opioid-drug-detox/heroin/': '/what-we-treat/opioid-addiction/',
    '/our-programs/medical-detox/drug-detox/opioid-drug-detox/oxycontin/': '/what-we-treat/opioid-addiction/',
    '/our-programs/medical-detox/drug-detox/opioid-drug-detox/vicodin/': '/what-we-treat/opioid-addiction/',
    '/our-programs/medical-detox/drug-detox/prescription-drug-detox/': '/what-we-treat/opioid-addiction/',
    '/our-programs/medical-detox/drug-detox/prescription-drug-detox/xanax/': '/what-we-treat/benzodiazepine-addiction/',
    '/our-programs/medical-detox/drug-detox/stimulant-drug-detox/': '/what-we-treat/stimulant-addiction/',
    '/our-programs/medical-detox/drug-detox/stimulant-drug-detox/cocaine/': '/what-we-treat/stimulant-addiction/',
    '/our-programs/medical-detox/drug-detox/stimulant-drug-detox/marijuana/': '/what-we-treat/',
    '/our-programs/medical-detox/drug-detox/stimulant-drug-detox/meth/': '/what-we-treat/stimulant-addiction/methamphetamine/',
    '/our-programs/medication-assisted-treatment-mat/': '/what-we-treat/opioid-addiction/',
    '/our-programs/outpatient-treatment/': '/programs/intensive-outpatient-iop/',
    '/our-programs/therapy/': '/therapies/',
    '/our-programs/therapy/12-step-program/': '/therapies/',
    '/our-programs/therapy/cognitive-behavioral-therapy/': '/therapies/',
    '/our-programs/therapy/grief-therapy/': '/therapies/',
    '/our-programs/therapy/group-therapy/': '/therapies/',
    '/our-programs/therapy/individual-counseling/': '/therapies/',
    '/our-programs/therapy/trauma-focused-therapy/': '/therapies/',
    '/our-programs/virtual-iop-treatment-arizona/': '/programs/intensive-outpatient-iop/',
    '/podcast/': '/resources/',
    '/privacy-policy/': '/',
    '/site-map/': '/sitemap/',
    '/tatum-ranch-arizona-facility/': '/',
    '/terms-of-use/': '/',
    '/the-2-different-types-of-addiction-with-examples/': '/what-we-treat/',
    '/tucson-facility/': '/',
    '/who-we-help/': '/who-we-serve/',
    '/who-we-help/professionals/': '/referrals/',
    '/who-we-help/professionals/impaired-physicians-program/': '/referrals/',
    '/who-we-help/young-adults/': '/who-we-serve/',
};

export default defineConfig({
  site: SITE,
  /* /medication-assisted-treatment was retired on 2026-09-04. Admissions states
     there is no methadone programme, so the page described a service that does
     not exist. It is redirected rather than deleted outright because the URL was
     live and indexed — anyone holding the link lands on the closest relevant
     page instead of a 404.

     The real 301 now lives in vercel.json, which is where the host can issue a
     proper permanent redirect. This Astro-level entry is kept as a fallback so
     the redirect still works in local dev and anywhere the site is served
     without Vercel's edge config. Keep both. */
  redirects: {
    ...MIGRATION_REDIRECTS,
    '/medication-assisted-treatment': '/what-we-treat/opioid-addiction/',
  },
  integrations: [
    sitemap({
      filter: (page) => !EXCLUDE.some((path) => page === `${SITE}${path}`),
    }),
  ],
  vite: {
    plugins: [tailwindcss()]
  }
});
